spring:
  cloud:
    function:
      definition: orderEventProducer;paymentProcessor;inventoryProcessor;shippingProcessor
    stream:
      default:
        producer:
          useNativeEncoding: true
      bindings:
        order-events-channel:
          destination: order-events
        paymentProcessor-in-0:
          destination: payment-events
          group: order-service-group
#        paymentProcessor-out-0:
#          destination: order-events
        inventoryProcessor-in-0:
          destination: inventory-events
          group: order-service-group
#        inventoryProcessor-out-0:
#          destination: order-events
        shippingProcessor-in-0:
          destination: shipping-events
          group: order-service-group
      kafka:
        binder:
          consumer-properties:
            "value.deserializer": org.springframework.kafka.support.serializer.JsonDeserializer
            "key.deserializer": org.apache.kafka.common.serialization.StringDeserializer
            "auto.offset.reset": "earliest"
            "spring.json.trusted.packages": "com.vinsguru.common.events.*"
          producer-properties:
            "value.serializer": org.springframework.kafka.support.serializer.JsonSerializer
            "key.serializer": org.apache.kafka.common.serialization.StringSerializer